# Generated by Django 5.2 on 2025-05-18 20:13

import django.contrib.auth.models
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True,
                                                    verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions '
                                                               'without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150,
                                                verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150,
                                               verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False,
                                                 help_text='Designates whether the user can log into this admin site.',
                                                 verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True,
                                                  help_text='Designates whether this user should be treated as active.'
                                                            ' Unselect this instead of deleting accounts.',
                                                  verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now,
                                                     verbose_name='date joined')),
                ('username', models.CharField(blank=True, help_text='Введите Ваше имя',
                                              max_length=25, null=True, verbose_name='Имя пользователя')),
                ('email', models.EmailField(help_text='Введите эл.почту', max_length=254,
                                            unique=True, verbose_name='Email')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128,
                                                                                null=True, region='RU',
                                                                                verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, help_text='Загрузите фото, по-желанию', null=True,
                                             upload_to='users/avatars/', verbose_name='Аватар')),
                ('country', models.CharField(blank=True, help_text='Ваша страна',
                                             max_length=25, null=True,
                                             verbose_name='Страна')),
                ('groups', models.ManyToManyField(blank=True,
                                                  related_name='user_set',
                                                  to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True,
                                                            related_name='user_permissions_set',
                                                            to='auth.permission')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
