# Generated by Django 5.2 on 2025-05-03 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок', max_length=100, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, help_text='Текст поста', null=True, verbose_name='Текстовый контент')),
                ('image', models.ImageField(blank=True, default='photos/blog/default_post.jpg', help_text='Загрузите изображение', null=True, upload_to='photos/blog', verbose_name='Изображение')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Дата обновления')),
                ('published', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
                'ordering': ['title', 'published', 'created_at', 'updated_at', 'views_count'],
            },
        ),
    ]
