# Generated by Django 5.2 on 2025-05-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['price'],
                     'permissions': [('can_unpublish_product', 'Может отменять публикацию')],
                     'verbose_name': 'Продукт',
                     'verbose_name_plural': 'Продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='продукт опубликован'),
        ),
    ]
